<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="Microsoft.TestPlatform.TestHost" Version="17.12.0" />
    <PackageReference Include="xunit.analyzers" Version="1.17.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="xunit.core" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\ASP.Api.Client\ASP.Api.Client.csproj" />
    <ProjectReference Include="..\..\src\ASP.Domain\ASP.Domain.csproj" />
    <ProjectReference Include="..\..\src\ASP.Core\ASP.Core.csproj" />
    <ProjectReference Include="..\..\src\ASP.Web.Core\ASP.Web.Core.csproj" />
    <ProjectReference Include="..\..\src\ASP.Web\ASP.Web.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="DfE.Data.ComponentLibrary.CleanArchitecture">
      <HintPath>..\..\lib\DfE.Data.ComponentLibrary.CleanArchitecture.dll</HintPath>
    </Reference>
    <Reference Include="DfE.Data.ComponentLibrary.Infrastructure.Persistence.CosmosDb">
      <HintPath>..\..\lib\DfE.Data.ComponentLibrary.Infrastructure.Persistence.CosmosDb.dll</HintPath>
    </Reference>
    <Reference Include="DfE.Data.DynamicPageTemplates.Web">
      <HintPath>..\..\lib\DfE.Data.DynamicPageTemplates.Web.dll</HintPath>
    </Reference>
  </ItemGroup>



</Project>
