trigger:
  branches:
    include:
    - main
      
variables:
  - template: pipelines/variables/common-var.yml
 
stages:
- stage: Build
  displayName: Build stage

  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)

    steps:
      - task: NuGetToolInstaller@1

      - task: NuGetCommand@2
        displayName: 'NuGet restore'
        inputs:
          restoreSolution: '**\*.sln'

      - task: Npm@1
        displayName: 'Install Node Packages'
        inputs:
          commands: 'install'  
          
      - task: Npm@1
        displayName: 'Run Webpack'
        inputs:
          commands: 'build-prod'  

      - task: VSBuild@1
        displayName: 'Build solution'
        inputs:
          msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactstagingdirectory)\\"'
          platform: '$(BuildPlatform)'
          configuration: '$(BuildConfiguration)'

      - task: VSTest@2
        displayName: 'Test Assemblies'
        inputs:
          testAssemblyVer2: |
            **\$(BuildConfiguration)\*test*.dll
            !**\obj\**
            platform: '$(BuildPlatform)'
            configuration: '$(BuildConfiguration)'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact'
        inputs:
          PathtoPublish: '$(build.artifactstagingdirectory)'
        condition: succeededOrFailed()
          

- stage: 'DeployDev'
  displayName: 'Deploy Dev stage '
  dependsOn: 'Build'
  jobs: 
  - template: 'pipelines/deployment-stage.yml'
    parameters:
      name: 'DeployDev'
      displayName: 'Deploy Dev stage'
      dependsOn: 'Build'
      jobName: 'Deploy'
      jobDisplayName: 'Deploy Dev '
      envName: Dev
      vmImageName: $(vmImageName)
      variableFile: variables/dev-var.yml
      azureSubscriptionName: s192d.azdo-deployment
      azureSubscriptionId: '212193cd-152c-4621-97d1-85cb63f025b4'