variables:
  - template: pipelines/variables/common-var.yml
 
stages:
- stage: Build
  displayName: Build stage

  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)

    steps:
      - task: NuGetToolInstaller@1

      - task: NuGetCommand@2
        displayName: 'NuGet restore'
        inputs:
          restoreSolution: '**\*.sln'

      - task: Npm@1
        displayName: 'Install Node Packages'
        inputs:
          command: 'install' 
          workingDir: '$(Build.SourcesDirectory)/src/asp.web'
          verbose: true
          
      - task: Npm@1
        displayName: 'Run Webpack'
        inputs:
          command: 'custom'
          customCommand: 'run build-prod' 
          workingDir: '$(Build.SourcesDirectory)/src/asp.web'
          verbose: true

      - task: VSBuild@1
        displayName: 'Build solution'
        inputs:
          msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactstagingdirectory)\\"'
          platform: '$(BuildPlatform)'
          configuration: '$(BuildConfiguration)'
    
      - task: VSTest@2
        displayName: 'Test Assemblies'
        inputs:
          testAssemblyVer2: |
            **\$(BuildConfiguration)\*[tT]est.dll
            **\$(BuildConfiguration)\**\*[tT]est.dll
            **\$(BuildConfiguration)\*[tT]ests.dll
            **\$(BuildConfiguration)\**\*[tT]ests.dll
            !**\obj\**
            !**\*Microsoft.TestPlatform*
            !**\*Microsoft.VisualStudio.TestPlatform*
            platform: '$(BuildPlatform)'
            configuration: '$(BuildConfiguration)'