<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <SpecFlowObsoleteCodeBehindFiles Remove="Features\HeadingComponent - Copy.feature.cs" />
    <SpecFlowObsoleteCodeBehindFiles Remove="Features\HomePage - Copy.feature.cs" />
    <SpecFlowObsoleteCodeBehindFiles Remove="Features\StaticContentPage - Copy.feature.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AngleSharp" Version="1.1.0" />
    <PackageReference Include="AngleSharp.Io" Version="1.0.0" />
    <PackageReference Include="AngleSharp.Js" Version="0.15.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="Microsoft.TestPlatform.TestHost" Version="17.8.0" />
    <PackageReference Include="SpecFlow.Plus.LivingDocPlugin" Version="3.9.57" />
    <PackageReference Include="SpecFlow.xUnit" Version="3.9.74" />
    <PackageReference Include="xunit" Version="2.4.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.3" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Drivers\" />
    <Folder Include="Support\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\ASP.Api\ASP.Api.csproj" />
    <ProjectReference Include="..\..\src\ASP.Core\ASP.Core.csproj" />
    <ProjectReference Include="..\..\src\ASP.Web\ASP.Web.csproj" />
    <ProjectReference Include="..\ASP.Test.Core\ASP.Test.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Features\ParagraphComponent.feature.cs">
      <DependentUpon>ParagraphComponent.feature</DependentUpon>
    </Compile>
    <Compile Update="Features\HeadingComponent.feature.cs">
      <DependentUpon>HeadingComponent.feature</DependentUpon>
    </Compile>
    <Compile Update="Features\HelpContent.feature.cs">
      <DependentUpon>HelpContent.feature</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <SpecFlowFeatureFiles Update="Features\ParagraphComponent.feature">
      <Visible>$(UsingMicrosoftNETSdk)</Visible>
      <CodeBehindFile>%(RelativeDir)%(Filename).feature$(DefaultLanguageSourceExtension)</CodeBehindFile>
    </SpecFlowFeatureFiles>
    <SpecFlowFeatureFiles Update="Features\HeadingComponent.feature">
      <Visible>$(UsingMicrosoftNETSdk)</Visible>
      <CodeBehindFile>%(RelativeDir)%(Filename).feature$(DefaultLanguageSourceExtension)</CodeBehindFile>
    </SpecFlowFeatureFiles>
    <SpecFlowFeatureFiles Update="Features\HelpContent.feature">
      <Visible>$(UsingMicrosoftNETSdk)</Visible>
      <CodeBehindFile>%(RelativeDir)%(Filename).feature$(DefaultLanguageSourceExtension)</CodeBehindFile>
    </SpecFlowFeatureFiles>
  </ItemGroup>

</Project>
