<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RunSettingsFilePath>$(MSBuildProjectDirectory)\test.runsettings</RunSettingsFilePath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AngleSharp" Version="1.1.0" />
    <PackageReference Include="AngleSharp.Io" Version="1.0.0" />
    <PackageReference Include="AngleSharp.Js" Version="0.15.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="Microsoft.TestPlatform.TestHost" Version="17.8.0" />
    <PackageReference Include="SpecFlow.Plus.LivingDocPlugin" Version="3.9.57" />
    <PackageReference Include="SpecFlow.xUnit" Version="3.9.74" />
    <PackageReference Include="xunit" Version="2.6.6" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\ASP.Core\ASP.Core.csproj" />
    <ProjectReference Include="..\..\src\ASP.Web\ASP.Web.csproj" />
    <ProjectReference Include="..\ASP.Test.Acceptance\ASP.Test.Acceptance.csproj" />
    <ProjectReference Include="..\ASP.Test.Core\ASP.Test.Core.csproj" />
    <ProjectReference Include="..\ASP.Test.Web\ASP.Test.Web.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="DfE.Data.ComponentLibrary.CleanArchitecture">
      <HintPath>..\..\lib\DfE.Data.ComponentLibrary.CleanArchitecture.dll</HintPath>
    </Reference>
    <Reference Include="DfE.Data.ComponentLibrary.Infrastructure.Persistence.CosmosDb">
      <HintPath>..\..\lib\DfE.Data.ComponentLibrary.Infrastructure.Persistence.CosmosDb.dll</HintPath>
    </Reference>
    <Reference Include="DfE.Data.DynamicPageTemplates.Web">
      <HintPath>..\..\lib\DfE.Data.DynamicPageTemplates.Web.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Features\Service\HomePage.feature.cs">
      <DependentUpon>HomePage.feature</DependentUpon>
    </Compile>
    <Compile Update="Features\Components\ParagraphView.feature.cs">
      <DependentUpon>ParagraphView.feature</DependentUpon>
    </Compile>
    <Compile Update="Features\Components\HeadingEdit.feature.cs">
      <DependentUpon>HeadingEdit.feature</DependentUpon>
    </Compile>
    <Compile Update="Features\Service\HelpPageView.feature.cs">
      <DependentUpon>HelpPageView.feature</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.Test.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="appsettings.Test.local.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="xunit.runner.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <SpecFlowFeatureFiles Update="Features\Components\Heading.feature">
      <Visible>$(UsingMicrosoftNETSdk)</Visible>
      <CodeBehindFile>%(RelativeDir)%(Filename).feature$(DefaultLanguageSourceExtension)</CodeBehindFile>
    </SpecFlowFeatureFiles>
    <SpecFlowFeatureFiles Update="Features\Components\ParagraphEdit.feature">
      <Visible>$(UsingMicrosoftNETSdk)</Visible>
      <CodeBehindFile>%(RelativeDir)%(Filename).feature$(DefaultLanguageSourceExtension)</CodeBehindFile>
    </SpecFlowFeatureFiles>
    <SpecFlowFeatureFiles Update="Features\Service\HelpPageEdit.feature">
      <Visible>$(UsingMicrosoftNETSdk)</Visible>
      <CodeBehindFile>%(RelativeDir)%(Filename).feature$(DefaultLanguageSourceExtension)</CodeBehindFile>
    </SpecFlowFeatureFiles>
    <SpecFlowFeatureFiles Update="Features\Service\HomePage.feature">
      <Visible>$(UsingMicrosoftNETSdk)</Visible>
      <CodeBehindFile>%(RelativeDir)%(Filename).feature$(DefaultLanguageSourceExtension)</CodeBehindFile>
    </SpecFlowFeatureFiles>
    <SpecFlowFeatureFiles Update="Features\Components\Paragraph.feature">
      <Visible>$(UsingMicrosoftNETSdk)</Visible>
      <CodeBehindFile>%(RelativeDir)%(Filename).feature$(DefaultLanguageSourceExtension)</CodeBehindFile>
    </SpecFlowFeatureFiles>
    <SpecFlowFeatureFiles Update="Features\Components\HeadingEdit.feature">
      <Visible>$(UsingMicrosoftNETSdk)</Visible>
      <CodeBehindFile>%(RelativeDir)%(Filename).feature$(DefaultLanguageSourceExtension)</CodeBehindFile>
    </SpecFlowFeatureFiles>
    <SpecFlowFeatureFiles Update="Features\Service\HelpPage.feature">
      <Visible>$(UsingMicrosoftNETSdk)</Visible>
      <CodeBehindFile>%(RelativeDir)%(Filename).feature$(DefaultLanguageSourceExtension)</CodeBehindFile>
    </SpecFlowFeatureFiles>
  </ItemGroup>

</Project>
