parameters:
- name: name
- name: displayName
- name: dependsOn
- name: jobName
- name: jobDisplayName
- name: envName
- name: vmImageName
- name: variableFile
- name: azureSubscriptionName
- name: azureSubscriptionId


jobs:
- deployment: ${{parameters.jobName}}
  displayName: ${{parameters.jobDisplayName}}
  environment: ${{parameters.envName}}

  variables:
  - template: ${{parameters.variableFile}}
  pool:
    vmImage: ${{parameters.vmImageName}}

  strategy:
    runOnce:
      deploy:
        steps:
        
        - task: DownloadPipelineArtifact@2
          displayName: 'Download Files'
          inputs:
            artifact: drop-web
            downloadPath: '$(System.ArtifactsDirectory)\files-web'

        - task: DownloadPipelineArtifact@2
          displayName: 'Download Files'
          inputs:
            artifact: drop-api
            downloadPath: '$(System.ArtifactsDirectory)\files-api'

        - task: AzureRmWebAppDeployment@4
          displayName: 'Azure App Service Deploy: $(appServiceName)'
          inputs:
            azureSubscription: ${{parameters.azureSubscriptionName}}
            WebAppName: '$(appServiceName)'
            packageForLinux: '$(System.ArtifactsDirectory)\files-web\**\ASP.Web.zip'
            appSettings: '-AzureKeyVault:KeyVaultName $(AzureKeyVault:KeyVaultName) -Api:InProcess $(Api:InProcess) -Api:EndpointBaseUrl $(Api:EndpointBaseUrl) -Api:FunctionsKey $(Api:FunctionsKey) -DsiOidc:Audience $(DsiOidc:Audience) -DsiOidc:CallbackPath $(DsiOidc:CallbackPath) -DsiOidc:Issuer $(DsiOidc:Issuer) -DsiOidc:MetadataAddress $(DsiOidc:MetadataAddress) -DsiOidc:ClientId $(DsiOidc:ClientId) -DsiOidc:SignedOutCallbackPath $(DsiOidc:SignedOutCallbackPath) -DsiOidc:SignedOutRedirectUri $(DsiOidc:SignedOutRedirectUri) -DsiOidc:ServiceId $(DsiOidc:ServiceId) -DsiOidc:SessionTimeout $(DsiOidc:SessionTimeout) -DsiOidc:ProfileUrl $(DsiOidc:ProfileUrl) -DsiPublicApi:Audience $(DsiPublicApi:Audience) -DsiPublicApi:AuthorizationUrl $(DsiPublicApi:AuthorizationUrl) -DsiPublicApi:ClientId $(DsiPublicApi:ClientId) -DocumentDatabase:ManagedIdentityClientId $(DocumentDatabase:ManagedIdentityClientId) -DocumentDatabase:DatabaseId $(DocumentDatabase:DatabaseId) -DocumentDatabase:EndpointUri $(DocumentDatabase:EndpointUri) -TableStorage:ManagedIdentityClientId $(TableStorage:ManagedIdentityClientId) -TableStorage:StorageAccountName $(TableStorage:StorageAccountName) -TableStorage:TableName $(TableStorage:TableName) -Search:PageSize $(Search:PageSize) -Search:MaxSearchSuggestions $(Search:MaxSearchSuggestions) -ASPNETCORE_ENVIRONMENT $(ASPNETCORE_ENVIRONMENT) -APPINSIGHTS_INSTRUMENTATIONKEY $(APPINSIGHTS_INSTRUMENTATIONKEY) -APPLICATIONINSIGHTS_CONNECTION_STRING $(APPLICATIONINSIGHTS_CONNECTION_STRING)'

        - task: AzureFunctionApp@2
          displayName: 'Azure Function App Deploy: $(functionAppName)'
          inputs:
            connectedServiceNameARM: ${{parameters.azureSubscriptionName}}
            appType: functionApp
            appName: '$(functionAppName)'
            package: '$(System.ArtifactsDirectory)\files-api\**\api.zip'
            appSettings: '-DocumentDatabase:ManagedIdentityClientId $(DocumentDatabase:ManagedIdentityClientId) -DocumentDatabase:EndpointUri $(DocumentDatabase:EndpointUri) -DocumentDatabase:DatabaseId $(DocumentDatabase:DatabaseId) -AzureKeyVault:KeyVaultName $(AzureKeyVault:KeyVaultName) -AzureWebJobsStorage $(AzureWebJobsStorage) -AzureWebJobsStorage__accountName $(StorageAccountName)'
