parameters:
- name: name
- name: displayName
- name: dependsOn
- name: jobName
- name: jobDisplayName
- name: envName
- name: vmImageName
- name: variableFile
- name: azureSubscriptionName
- name: azureSubscriptionId


jobs:
- deployment: ${{parameters.jobName}}
  displayName: ${{parameters.jobDisplayName}}
  environment: ${{parameters.envName}}

  variables:
  - template: ${{parameters.variableFile}}
  pool:
    vmImage: ${{parameters.vmImageName}}

  strategy:
    runOnce:
      deploy:
        steps:
        
        - task: DownloadPipelineArtifact@2
          displayName: 'Download Files'
          inputs:
            artifact: drop-web
            downloadPath: '$(System.ArtifactsDirectory)\files-web'

        - task: DownloadPipelineArtifact@2
          displayName: 'Download Files'
          inputs:
            artifact: drop-api
            downloadPath: '$(System.ArtifactsDirectory)\files-api'

        - task: AzureRmWebAppDeployment@4
          displayName: 'Azure App Service Deploy: $(appServiceName)'
          inputs:
            azureSubscription: ${{parameters.azureSubscriptionName}}
            WebAppName: '$(appServiceName)'
            packageForLinux: '$(System.ArtifactsDirectory)\files-web\**\ASP.Web.zip'
            appSettings: '-Api:EndpointBaseUrl $(Api:EndpointBaseUrl) -Api:FunctionsKey $(Api:FunctionsKey) -Api:InProcess $(Api:InProcess) -APPINSIGHTS_INSTRUMENTATIONKEY $(APPINSIGHTS_INSTRUMENTATIONKEY) -APPLICATIONINSIGHTS_CONNECTION_STRING $(APPLICATIONINSIGHTS_CONNECTION_STRING) -ASPNETCORE_ENVIRONMENT $(ASPNETCORE_ENVIRONMENT) -AzureKeyVault:KeyVaultName $(AzureKeyVault:KeyVaultName) -BlobStorage:ManagedIdentityClientId $(BlobStorage:ManagedIdentityClientId) -BlobStorage:StorageAccountName $(BlobStorage:StorageAccountName) -DocumentDatabase:EndpointUri $(DocumentDatabase:EndpointUri) -DocumentDatabase:ManagedIdentityClientId $(DocumentDatabase:ManagedIdentityClientId) -DsiOidc:Audience $(DsiOidc:Audience) -DsiOidc:ClientId $(DsiOidc:ClientId) -DsiOidc:Issuer $(DsiOidc:Issuer) -DsiOidc:MetadataAddress $(DsiOidc:MetadataAddress) -DsiOidc:ProfileUrl $(DsiOidc:ProfileUrl) -DsiOidc:RedirectUrlAfterSignout $(DsiOidc:RedirectUrlAfterSignout) -DsiOidc:ServiceId $(DsiOidc:ServiceId) -DsiOidc:SessionTimeout $(DsiOidc:SessionTimeout) -DsiPublicApi:AuthorizationUrl $(DsiPublicApi:AuthorizationUrl) -DsiPublicApi:ClientId $(DsiPublicApi:ClientId) -ErrorHandling:ForceProductionErrorPage $(ErrorHandling:ForceProductionErrorPage) -ErrorHandling:ShowStackTrace $(ErrorHandling:ShowStackTrace) -Search:MaxSearchSuggestions $(Search:MaxSearchSuggestions) -Search:PageSize $(Search:PageSize) -TableStorage:ManagedIdentityClientId $(TableStorage:ManagedIdentityClientId) -TableStorage:StorageAccountName $(TableStorage:StorageAccountName)'

        - task: AzureFunctionApp@2
          displayName: 'Azure Function App Deploy: $(functionAppName)'
          inputs:
            connectedServiceNameARM: ${{parameters.azureSubscriptionName}}
            appType: functionApp
            appName: '$(functionAppName)'
            package: '$(System.ArtifactsDirectory)\files-api\**\api.zip'
            appSettings: '-ASPNETCORE_ENVIRONMENT $(ASPNETCORE_ENVIRONMENT) -APPINSIGHTS_INSTRUMENTATIONKEY $(APPINSIGHTS_INSTRUMENTATIONKEY) -APPLICATIONINSIGHTS_CONNECTION_STRING $(APPLICATIONINSIGHTS_CONNECTION_STRING)' -AzureKeyVault:KeyVaultName $(AzureKeyVault:KeyVaultName) -AzureWebJobsStorage $(AzureWebJobsStorage) -AzureWebJobsStorage__accountName $(AzureWebJobsStorage__accountName) -BlobStorage:ManagedIdentityClientId $(BlobStorage:ManagedIdentityClientId) -BlobStorage:StorageAccountName $(BlobStorage:StorageAccountName) -DocumentDatabase:EndpointUri $(DocumentDatabase:EndpointUri) -DocumentDatabase:ManagedIdentityClientId $(DocumentDatabase:ManagedIdentityClientId) -ErrorHandling:ShowStackTrace $(ErrorHandling:ShowStackTrace)'