parameters:
- name: name
- name: displayName
- name: dependsOn
- name: jobName
- name: jobDisplayName
- name: envName
- name: vmImageName
- name: variableFile
- name: azureSubscriptionName
- name: azureSubscriptionId


jobs:
- deployment: ${{parameters.jobName}}
  displayName: ${{parameters.jobDisplayName}}
  environment: ${{parameters.envName}}

  variables:
  - template: ${{parameters.variableFile}}
  pool:
    vmImage: ${{parameters.vmImageName}}

  strategy:
    runOnce:
      deploy:
        steps:
        
        - task: DownloadPipelineArtifact@2
          displayName: 'Download Files'
          inputs:
            artifact: drop-web
            downloadPath: '$(System.ArtifactsDirectory)\files-web'

        - task: DownloadPipelineArtifact@2
          displayName: 'Download Files'
          inputs:
            artifact: drop-api
            downloadPath: '$(System.ArtifactsDirectory)\files-api'

        - task: AzureRmWebAppDeployment@4
          displayName: 'Azure App Service Deploy: $(appServiceName)'
          inputs:
            azureSubscription: ${{parameters.azureSubscriptionName}}
            WebAppName: '$(appServiceName)'
            packageForLinux: '$(System.ArtifactsDirectory)\files-web\**\ASP.Web.zip'
            appSettings: '-AspAzureKeyVaultName $(AspAzureKeyVaultName) -DsiOidc:DsiAudience $(DsiOidc:DsiAudience) -DsiOidc:DsiCallbackPath $(DsiOidc:DsiCallbackPath) -DsiOidc:DsiIssuer $(DsiOidc:DsiIssuer) -DsiOidc:DsiMetadataAddress $(DsiOidc:DsiMetadataAddress) -DsiOidc:DsiOidcClientId $(DsiOidc:DsiOidcClientId) -DsiOidc:DsiRedirectUrlAfterSignout $(DsiOidc:DsiRedirectUrlAfterSignout) -DsiOidc:DsiSignedOutCallbackPath $(DsiOidc:DsiSignedOutCallbackPath) -DsiOidc:DsiSignedOutRedirectUri $(DsiOidc:DsiSignedOutRedirectUri) -DsiOidc:SessionTimeout $(DsiOidc:SessionTimeout) -DsiOidc:DsiProfileUrl $(DsiOidc:DsiProfileUrl) -DsiPublicApi:DsiApiAudience $(DsiPublicApi:DsiApiAudience) -DsiPublicApi:DsiApiAuthorizationUrl $(DsiPublicApi:DsiApiAuthorizationUrl) -DsiPublicApi:DsiApiClientId $(DsiPublicApi:DsiApiClientId) -RepositoryOptions:DatabaseId $(RepositoryOptions:DatabaseId) -RepositoryOptions:EndpointUri $(RepositoryOptions:EndpointUri) -TableStorage:ManagedIdentityClientId $(TableStorage:ManagedIdentityClientId) -TableStorage:StorageAccountName $(TableStorage:StorageAccountName) -TableStorage:TableName $(TableStorage:TableName) -ASPNETCORE_ENVIRONMENT $(ASPNETCORE_ENVIRONMENT) -APPINSIGHTS_INSTRUMENTATIONKEY $(APPINSIGHTS_INSTRUMENTATIONKEY) -APPLICATIONINSIGHTS_CONNECTION_STRING $(APPLICATIONINSIGHTS_CONNECTION_STRING)'

        - task: AzureFunctionApp@2
          displayName: 'Azure Function App Deploy: $(functionAppName)'
          inputs:
            connectedServiceNameARM: ${{parameters.azureSubscriptionName}}
            appType: functionApp
            appName: '$(functionAppName)'
            package: '$(System.ArtifactsDirectory)\files-api\**\api.zip'
            appSettings: '-RepositoryOptions:EndpointUri $(RepositoryOptions:EndpointUri) -RepositoryOptions:DatabaseId $(RepositoryOptions:DatabaseId) -AspAzureKeyVaultName $(AspAzureKeyVaultName) -AzureWebJobsStorage__accountName $(StorageAccountName)'
