<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RunSettingsFilePath>$(MSBuildProjectDirectory)\test.runsettings</RunSettingsFilePath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore" Version="1.2.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="8.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="Microsoft.TestPlatform.TestHost" Version="17.12.0" />
    <PackageReference Include="SpecFlow.Plus.LivingDocPlugin" Version="3.9.57" />
    <PackageReference Include="SpecFlow.xUnit" Version="3.9.74" />
    <PackageReference Include="xunit.analyzers" Version="1.17.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="xunit.core" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="FluentAssertions" Version="6.12.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\ASP.Api\ASP.Api.csproj" />
    <ProjectReference Include="..\..\src\ASP.Core\ASP.Core.csproj" />
    <ProjectReference Include="..\..\src\ASP.Api.Client.InProcess\ASP.Api.Client.InProcess.csproj" />
    <ProjectReference Include="..\ASP.Test.SpecFlow\ASP.Test.SpecFlow.csproj" />
    <ProjectReference Include="..\ASP.Test.Core\ASP.Test.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="local.settings.template.test.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="xunit.runner.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <SpecFlowFeatureFiles Update="Features\EstablishmentSearch.feature">
      <Visible>$(UsingMicrosoftNETSdk)</Visible>
      <CodeBehindFile>%(RelativeDir)%(Filename).feature$(DefaultLanguageSourceExtension)</CodeBehindFile>
    </SpecFlowFeatureFiles>
    <SpecFlowFeatureFiles Update="Features\GetEstablishmentDetails.feature">
      <Visible>$(UsingMicrosoftNETSdk)</Visible>
      <CodeBehindFile>%(RelativeDir)%(Filename).feature$(DefaultLanguageSourceExtension)</CodeBehindFile>
    </SpecFlowFeatureFiles>
    <SpecFlowFeatureFiles Update="Features\UpdateContentTemplate.feature">
      <Visible>$(UsingMicrosoftNETSdk)</Visible>
      <CodeBehindFile>%(RelativeDir)%(Filename).feature$(DefaultLanguageSourceExtension)</CodeBehindFile>
    </SpecFlowFeatureFiles>
    <SpecFlowFeatureFiles Update="Features\GetContentTemplate.feature">
      <Visible>$(UsingMicrosoftNETSdk)</Visible>
      <CodeBehindFile>%(RelativeDir)%(Filename).feature$(DefaultLanguageSourceExtension)</CodeBehindFile>
    </SpecFlowFeatureFiles>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Features\GetEstablishmentDetails.feature.cs">
      <Visible>true</Visible>
      <DependentUpon>GetEstablishmentDetails.feature</DependentUpon>
      <DesignTime>true</DesignTime>
      <AutoGen>true</AutoGen>
    </Compile>
    <Compile Update="Features\GetMultiAcademyTrust.feature.cs">
      <DependentUpon>GetMultiAcademyTrust.feature</DependentUpon>
      <AutoGen>true</AutoGen>
      <DesignTime>true</DesignTime>
      <Visible>true</Visible>
    </Compile>
    <Compile Update="Features\GetAllLocalAuthorities.feature.cs">
      <DependentUpon>GetAllLocalAuthorities.feature</DependentUpon>
      <AutoGen>true</AutoGen>
      <DesignTime>true</DesignTime>
      <Visible>true</Visible>
    </Compile>
  </ItemGroup>

</Project>
