<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\ASP.Application\ASP.Application.csproj" />
		<ProjectReference Include="..\ASP.Core\ASP.Core.csproj" />
		<ProjectReference Include="..\ASP.Infrastructure\ASP.Infrastructure.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="GracefulExpandoObject.Json" Version="1.6.0" />
		<PackageReference Include="Microsoft.Azure.Cosmos" Version="3.37.1" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
	</ItemGroup>

	<ItemGroup>
	  <Reference Include="DfE.Data.ComponentLibrary.CleanArchitecture">
	    <HintPath>..\ASP.Application\Libraries\DfE.Data.ComponentLibrary.CleanArchitecture.dll</HintPath>
	  </Reference>
	  <Reference Include="DfE.Data.ComponentLibrary.Infrastructure.Persistence.CosmosDb">
	    <HintPath>..\ASP.Infrastructure\Libraries\DfE.Data.ComponentLibrary.Infrastructure.Persistence.CosmosDb.dll</HintPath>
	  </Reference>
	  <Reference Include="DfE.Data.DynamicPageTemplates.Web">
	    <HintPath>Libraries\DfE.Data.DynamicPageTemplates.Web.dll</HintPath>
	  </Reference>
	</ItemGroup>

</Project>
