<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<Content Include="Scripts\alpine.js" />
		<Content Include="Scripts\govukfrontendcss.js" />
		<Content Include="Scripts\govukfrontendjs.js" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\ASP.Application\ASP.Application.csproj" />
		<ProjectReference Include="..\ASP.Core\ASP.Core.csproj" />
		<ProjectReference Include="..\ASP.Infrastructure\ASP.Infrastructure.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="wwwroot\" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="DfE.Data.DynamicPageTemplates.Web" Version="2.0.19-beta-CI-20240205-150456" />
		<PackageReference Include="GracefulExpandoObject.Json" Version="1.6.0" />
		<PackageReference Include="Microsoft.Azure.Cosmos" Version="3.37.1" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
	</ItemGroup>

</Project>
