<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Scripts\alpine.js" />
    <Content Include="Scripts\govukfrontendcss.js" />
    <Content Include="Scripts\govukfrontendjs.js" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ASP.Application\ASP.Application.csproj" />
    <ProjectReference Include="..\ASP.Core\ASP.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

</Project>
