<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Establishments\**" />
    <EmbeddedResource Remove="Establishments\**" />
    <None Remove="Establishments\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ASP.Core\ASP.Core.csproj" />
    <ProjectReference Include="..\ASP.Domain\ASP.Domain.csproj" />
    <ProjectReference Include="..\ASP.Infrastructure\ASP.Infrastructure.csproj" />
  </ItemGroup>

</Project>
