<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <AzureFunctionsVersion>v4</AzureFunctionsVersion>
        <OutputType>Exe</OutputType>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
        <WarningLevel>9999</WarningLevel>
        <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
        <EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
        <GenerateDocumentationFile>True</GenerateDocumentationFile>
        <NoWarn>1701;1702;1591</NoWarn>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
        <WarningLevel>9999</WarningLevel>
        <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
        <EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
        <GenerateDocumentationFile>True</GenerateDocumentationFile>
        <NoWarn>1701;1702;1591</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.22.0" />
        <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.1.0" />
        <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore" Version="1.2.1" />
        <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.OpenApi" Version="1.5.1" />
        <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.17.2" />
        <PackageReference Include="Microsoft.ApplicationInsights.WorkerService" Version="2.22.0" />
        <PackageReference Include="Microsoft.Azure.Functions.Worker.ApplicationInsights" Version="1.2.0" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
        <PackageReference Include="Azure.Identity" Version="1.11.4" />
        <PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\ASP.Api.Client\ASP.Api.Client.csproj" />
        <ProjectReference Include="..\ASP.Domain.Repositories\ASP.Domain.Repositories.csproj" />
        <ProjectReference Include="..\ASP.Domain\ASP.Domain.csproj" />
        <ProjectReference Include="..\ASP.Infrastructure.Azure\ASP.Infrastructure.Azure.csproj" />
        <ProjectReference Include="..\ASP.Infrastructure\ASP.Infrastructure.csproj" />
    </ItemGroup>
    <ItemGroup>
        <Reference Include="DfE.Data.ComponentLibrary.CleanArchitecture">
            <HintPath>..\..\lib\DfE.Data.ComponentLibrary.CleanArchitecture.dll</HintPath>
        </Reference>
        <Reference Include="DfE.Data.ComponentLibrary.Infrastructure.Persistence.CosmosDb">
            <HintPath>..\..\lib\DfE.Data.ComponentLibrary.Infrastructure.Persistence.CosmosDb.dll</HintPath>
        </Reference>
    </ItemGroup>
    <ItemGroup>
        <Content Remove="local.settings.json" />
    </ItemGroup>

    <ItemGroup>
        <None Remove="local.settings.template.json" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="local.settings.template.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
        </Content>
    </ItemGroup>

    <ItemGroup>
        <None Update="host.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>
    <ItemGroup>
        <Using Include="System.Threading.ExecutionContext" Alias="ExecutionContext" />
    </ItemGroup>
</Project>