<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DfE.Data.ComponentLibrary.CrossCuttingConcerns.Json" Version="2.0.23-beta-CI-20231213-100114" />
    <PackageReference Include="DfE.Data.ComponentLibrary.Infrastructure.Persistence.CosmosDb" Version="2.0.23-beta-CI-20231213-100114" />
    <PackageReference Include="DfE.Data.DynamicPageTemplates.Web" Version="2.0.18-beta-CI-20240130-154119" />
    <PackageReference Include="Microsoft.Azure.Cosmos" Version="3.37.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ASP.Core\ASP.Core.csproj" />
  </ItemGroup>

</Project>
